### ISSUE TITLE
draw_gridlines called but function is commented

### ISSUE THREAD

**Issue by nrgiroux** [MaayanLab/clustergrammer#11]
index.js
enter_exit_update.js
are still calling draw_gridlines

**Comment by cornhundred** [comment]
Thanks, we can clean this up (we disabled the drawing of gridlines). Feel free to submit a pull request if you would like.

**Comment by cornhundred** [comment]
We're reenabling draw_gridlines, thanks for the issue.

**Comment by nrgiroux** [comment]
Hi,

Will the example page be synced ?
By the way the example page still has the slider issue in Firefox (I saw
you fixed it in the code).

Thanks again

2018-03-22 11:17 GMT-04:00 Nicolas Fernandez <notifications@github.com>:

**Comment by cornhundred** [comment]
Hi,

Are you referring to these example pages?

http://maayanlab.github.io/clustergrammer/scrolling_tour
http://maayanlab.github.io/clustergrammer/

We have just updated them by fast forwarding the gh-pages branch to the master branch. 

Best,
Nick

**Comment by nrgiroux** [comment]
Hello,

Yes these pages.
In Firefox the sliders' triangles and the clusters' trapezoids are missing.




2018-03-22 11:58 GMT-04:00 Nicolas Fernandez <notifications@github.com>:

**Comment by cornhundred** [comment]
Yes, Firefox appears to have a problem displaying SVG paths in Clustergrammer (the slider triangle and trapezoids are drawn using SVG paths). We recommend using Chrome, but we will look into the issue more in the future.

**Comment by nrgiroux** [comment]
Hi Nicolas,
I am pretty sure it was fixed in your code because I was about to do a pull request with this:

```
-- var output_string = 'M' + start_x + ',' + start_y + ', L' + mid_x + ', ' + mid_y + ', L' + final_x + ',' + final_y + ' Z';

++ var output_string = 'M' + start_x + ',' + start_y + ' L' + mid_x + ', ' + mid_y + ' L' + final_x + ',' + final_y + ' Z';
 
```
in these files:
clustergrammer\src\dendrogram\build_svg_dendro_slider.js
clustergrammer\src\dendrogram\make_dendro_crop_buttons.js
clustergrammer\src\dendrogram\make_dendro_triangles.js

but turned out the changes were there unless I looked too fast at those subtle changes.
So here they are if you need them !

**Comment by cornhundred** [comment]
Thanks, do those changes help with rendering triangles/paths in Firefox?

**Comment by nrgiroux** [comment]
Yes, specifically for SVG path in Firefox.

2018-03-29 12:04 GMT-04:00 Nicolas Fernandez <notifications@github.com>:

**Comment by cornhundred** [comment]
Cool, if you want to do a pull request I can check it on my end and merge it.

**Comment by cornhundred** [comment]
That worked great! Thanks again 👍I'll be releasing a new version with this fix.
