### ISSUE TITLE
Wider space between clusters

### ISSUE THREAD

**Issue by nrgiroux** [MaayanLab/clustergrammer#12]
Hi,

I am forking Clustergrammer and would like to add a wider space between clusters like this:
![image](https://user-images.githubusercontent.com/3594907/33385210-09f234b6-d4f6-11e7-9145-94b3a080b2bd.png)

This should be dynamic as well.
Is it possible to do it 'easily' ?
Could you point me where to begin please.

Thanks,
Richard

**Comment by cornhundred** [comment]
Hi Richard, 

It probably won't be too easy, but it is doable. To do that you should have a look at where the dimensions for the visualization are calculated (see [calc_viz_params.js](https://github.com/MaayanLab/clustergrammer/blob/master/src/params/calc_viz_params.js)). You will also have to modify the positioning of the rows/columns in [calc_matrix_params.js](https://github.com/MaayanLab/clustergrammer/blob/master/src/params/calc_matrix_params.js). Sorry that's not too specific, let us know how your progress goes. 

Best,
Nick
