### ISSUE TITLE
Obtaining similarity matrices

### ISSUE THREAD

**Issue by nrgiroux** [MaayanLab/clustergrammer#13]
Hi,

I am trying to get similarity matrices like shown on the web app demo page.
My set up is as follow:

- a front end formatting data to tsv, requesting a 'net.viz' from a:
- 'minimally forked' clustergrammer_py_v1_13_4 returning a net.cluster( ) response to a:
- forked Clustergrammer.js

From this setup I can get a "clustergram/heatmap".
What I am missing is: 
- do I have to format the request matrix differently to get a similarity matrix back ?
- do I have to modify request parameters (like sim_mat=true) ?

In the demo pages I see these two objects:
var network_sim_row 
var network_sim_col 
but I don't know how to get them.

Thank you,
Richard

**Comment by cornhundred** [comment]
Hi Richard, 

Yes, you have to use the argument `sim_mat=True` in Clustergrammer-PY (see the `cluster` method [here](http://clustergrammer.readthedocs.io/clustergrammer_py.html#clustergrammer_py.Network.cluster) for more information). Then you can get the `sim_row` or `sim_col` JSON using the `write_json_to_file` method of Clustergrammer-PY (see [make_clustergrammer.py](https://github.com/MaayanLab/clustergrammer/blob/master/make_clustergrammer.py#L41) which can be used to generate a heatmap and two similarity matrices from a TSV). You do not have to change the format of the input TSV. 

Let us know if that worked and we will make this clearer in the documentation. 

Best,
Nick

**Comment by nrgiroux** [comment]
Hi Nick,

Thank you very much for your so fast answer !
It helped me a lot. I ended up using export_data.export_net_json as we would be as file-less as possible.

By the way Clustergrammer is really great ! 
Your code is so tight and well done !

Thanks again,
Richard

**Comment by cornhundred** [comment]
Hi Richard, 

Thanks, I'm glad that worked out :) 

Best,
Nick
