### ISSUE TITLE
visualizing heatmap without clustering

### ISSUE THREAD

**Issue by raphael-upmc** [MaayanLab/clustergrammer#15]
Hi there,

first of all, I would like to acknowledge you for this very nice tool, it saves me a lot of time!

Here is my issue, I ran clustergrammer on my binary matrix, the results are good but I would like to rotate the branches of the hierarchical tree to get a nicer heatmap. 

So I order my matrix as my convenience and now I would like to visualize it using Clustergrammer but with no clustering. Unfortunately, I'm unable to do this. I tried the option run_clustering=False, the Json file is created but I get an error when I load the webpage.

Is there a way to visualize the heatmap without cluster it ?

all the best

raphael

**Comment by cornhundred** [comment]
Hi Raphael, 

Glad you are finding Clustergrammer useful. The latest release (v1.19.5) should render unclustered (`run_clustering=False` for Clustergrammer-PY) correctly. There is a small issue with the matrix 'spilling over' on the right side and I will work on cleaning that up soon. This issue is also being worked on for Clustergrammer-Widget [here](https://github.com/MaayanLab/clustergrammer-widget/issues/5). Let us know if that works

Best,
Nick

**Comment by raphael-upmc** [comment]
thank you Nick for this quick answer. Actually the python API seems to work well (or at least does not raise an error). The error happens when I try to generate the html webpage. I get this JS error :

Uncaught TypeError: Cannot set property 'row' of undefined clustergrammer.v1.19.4.js:11530 undefined
    at ini_viz_params (clustergrammer.v1.19.4.js:11530)
    at calc_viz_params (clustergrammer.v1.19.4.js:11429)
    at make_params (clustergrammer.v1.19.4.js:728)
    at Clustergrammer (clustergrammer.v1.19.4.js:96)
    at load_viz_new (coreGenomeCprModule.html:124)
    at coreGenomeCprModule.html:183
Uncaught ReferenceError: cgm is not defined coreGenomeCprModule.html:121 
    at coreGenomeCprModule.html:121
    at d3.js:1119

**Comment by cornhundred** [comment]
I see in the error that you are with `clustergrammer.v1.19.4.js`, can you retry using the latest version of Clustergrammer-JS `v1.19.5` (see [releases](https://github.com/MaayanLab/clustergrammer/releases)). I was able to get it working on my end. Let me know if that helps.

**Comment by raphael-upmc** [comment]
it works with the latest version of clustergrammer.js. Many thanks

Raph
