### ISSUE TITLE
Column Headers Need More Space

### ISSUE THREAD

**Issue by GrantPayneDenver** [MaayanLab/clustergrammer#17]
Hi again,

So, we noticed another thing about the heatmap links (awesome heatmaps though!) generated and returned by the API. There isn't a lot of room for column headers, although a context blurb does appear nicely when the cursor hovers over it. But if the header is over several characters long, it gets truncated. Like so:
![image](https://user-images.githubusercontent.com/4261977/38532045-32b519c6-3c30-11e8-8e4f-ad843ab2778a.png)

The usual header is something like "3 Mouse Lung Cancer - specimen grey mouse 33".

Is there perhaps an argument that could be included to allow for space above the table during the Post?

Cheers,
Grant

**Comment by cornhundred** [comment]
Hi Grant, 

The column label size can not currently be increased through the web application. The column label size can be increased using the [`col_label_scale`](http://clustergrammer.readthedocs.io/clustergrammer_js.html#Clustergrammer.args.row_label_scale,%20args.col_label_scale.) argument if you are building your own heatmaps using [Clustergrammer-JS](http://clustergrammer.readthedocs.io/clustergrammer_js.html#). For information on adding the visualization to your page please see the [docs](http://clustergrammer.readthedocs.io/building_webpage.html#adding-clustergrammer-to-a-page).

However, adding this as an argument to the post request is something that we can do in the future. 

Let us know if that helps and thanks for the feedback.

Best,
Nick

**Comment by JoshuaFortriede** [comment]
Grant,

I was able to make mine better by setting the 2 following parameters in the initial args dictionary.
1). 'col_label_scale' : 1.4   //This seems to increase the available height allowed for the labels
2). 'max_allow_fs' : 14  // This sets the maximum font size (in px) that at least the column and row labels can be.  The default is 20 which can be too big when using long names.  

Hope this helps.  I also wonder if there is something that could be done (feature request) where the column label will rap to two lines if enough height is available.

**Comment by cornhundred** [comment]
Hi @JoshuaFortriede, we are planning on implementing a user resizable column/row label area (e.g. dragging). This will be implemented for Clustergrammer-GL first https://github.com/ismms-himc/clustergrammer-gl.
