### ISSUE TITLE
Clustergrammer.min.js but un-obfuscated

### ISSUE THREAD

**Issue by mohammadbashir** [MaayanLab/clustergrammer#19]
Hello,
First I want to thank you for this library, really powerful and efficient!
I am only able to use the clustergrammer.min.js (since it is a single independent file) in my project.

The minified version is working perfectly! However when trying to edit the obfuscation is frustrating to edit/debug i tried to beautify it but still the variable names are too confusing. I also tried using the source map but it didn't work on chrome.

Can you please include a minified version of the library but without obfuscation? It would be of great help!

Thank you,
Mohammad Bashir Sidani.

**Comment by cornhundred** [comment]
Hi Mohammad, 

We're glad you like Clustergrammer. I'm not sure how to prevent obfuscation in the minification process, but I would recommend two things: 

1) try again to use the un-minified bundle clustergrammer.js (in my experience they should be interchangeable). You could also test out an older release of clustergrammer.js if you are having issues.

2) Since editing the large bundled JavaScript file is difficult, you can try editing from the [source code](https://github.com/MaayanLab/clustergrammer/tree/master/src) and bundling an updated version of clustergrammer.js using Webpack. 

Let us know if that helps or if you have questions on bundling with Webpack.

Best,
Nick

**Comment by mohammadbashir** [comment]
Hello,

The second option seems reasonable. What I did at first is that I edited the clustergrammer.js to fit my needs. After that I hosted locally the index.html (localhost) and everything was working perfectly with my changes.

Also replacing clustergrammer.js with clustergrammer.min.js from index.html works as well (but all the functions are the native that you have of course)

Now is there a way to generate clustergrammer.min.js from my clustergrammer.js that I edited?

I never worked with Webpack so if you can advice how to generate it it would be great!

**Comment by cornhundred** [comment]
Hi, 

Currently clustergrammer.min.js can only be generated from the source code using Webpack. I also think that [clustergrammer.js](https://github.com/MaayanLab/clustergrammer/blob/master/clustergrammer.js) should also operate as a standalone file just as clustergrammer.min.js.

To run webpack you need to have node and npm. Then you will run `npm install` in the base directory, which uses the [package.json](https://github.com/MaayanLab/clustergrammer/blob/master/package.json) to install dependencies. Then you can run `webpack --watch` from the base directory and this will use the [webpack.config](https://github.com/MaayanLab/clustergrammer/blob/master/webpack.config.js) to build the bundled versions of clustergrammer from the source code. It should also have browser-sync working, which will reload the page each time you modify the source code. 

Let us know if that helps out. 

Best,
Nick

**Comment by mohammadbashir** [comment]
Thanks! I will give the webpack a try and update you soon.

clustergrammer.js being a standalone is great news!

However when trying to use the .js instead of .min.js the js compiler fails to save it with errors such as:
1- "function ini_viz_params(params, predefined_cat_colors = true)" cannot use '=' 
2= "function(...args) {" cannot define '.'

But in the min it compiles fine

Best Regards,
Mohammad Bashir Sidani.

**Comment by cornhundred** [comment]
The `cannot use '='` error looks like an ES6 issue with [default parameters](https://www.sitepoint.com/es6-default-parameters/), so you might need to tell your JS compiler to use ES6. What compiler are you using?

**Comment by mohammadbashir** [comment]
I'm trying to include the Javascript inside of PEGA platform. I don't think it supports ES6 though. Meanwhile I installed node and npm, however on webpack --wath I am getting this now:

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.

**Comment by cornhundred** [comment]
That sounds like they are telling you to switch to using `config.optimization.minimize` instead of the `UglifyJsPlugin` (which may have been deprecated). I'm using the same version of webpack and will have a closer look later.

**Comment by mohammadbashir** [comment]
Hello,
After looking into it, turned out I should convert the ES6 code to ES5 since PEGA javascript compiler does not support ES6 yet. I found this online tool that does that job: [Online Coverter Tool](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code)

As you mentioned that the clustergrammer.js is a stand alone by itself, converting it through this tool to ES5 did the trick. Now it is working as it should!

Thanks for your quick and prompt feedback! looking forward to use this library :+1:
