### ISSUE TITLE
still planning to implement webgl version?

### ISSUE THREAD

**Issue by hyoo** [MaayanLab/clustergrammer#22]
Hello, thanks for making such a great tool. I like the clustergrammer and now we're testing it. Btw, I read from your paper that you were planning to build webgl version to incorporate larger dataset. How is it going? we wish to load ~500 genomes by ~10/15k features.

**Comment by cornhundred** [comment]
Hi,

Hi, we're glad you like Clustergrammer. Yes, we're working on the WebGL version of Clustergrammer ([Clustergrammer-GL](https://github.com/cornhundred/clustergrammer-gl) and a new WebGL Jupyter widget [Clustergrammer-Glidget](https://github.com/cornhundred/clustergrammer_glidget)), but it is still under heavy development. Feel free to have a look at the linked repos and we can keep you up to date as things start to finalize. Here's a link to a Jupyter notebook showing the old and new widgets: [CCLE Clustergrammer Glidget Jupyter notebook](http://nbviewer.jupyter.org/github/cornhundred/clustergrammer_glidget/blob/master/Clustergrammer-Glidget_CCLE.ipynb). Also, here's a [link](https://cornhundred.github.io/clustergrammer2-alpha/) to a visualization with 25,000 rows (visualizing the CyTOF data included in the [paper](https://www.nature.com/articles/sdata2017151).

In terms of matrix size, I've been able to visualize matrices with about 7-10 million matrix-cells (e.g. 1000 cell lines with 7,000-10,000 genes using a 2017 iMac), but this depends on your graphics card. Your matrix of 500 genomes (columns) and 10,000 features (rows) ends up being >5 million matrix cells. So, it could work but your [Visualization-JSON](https://clustergrammer.readthedocs.io/clustergrammer_js.html?highlight=visualization%20json#visualization-json) file will be large.

Let us know if you have any questions or feature requests.

Best,
Nick

**Comment by cornhundred** [comment]
Hi @hyoo, I'm closing this issue since we are currently actively developing Clustergrammer-GL https://github.com/ismms-himc/clustergrammer-gl. Please let us know if you have any feedback.
