### ISSUE TITLE
Clustergrammer Dendrogram JSON Generation

### ISSUE THREAD

**Issue by AndrewGuard** [MaayanLab/clustergrammer#26]
I am trying to integrate clustergrammer into a scientific site by generating the visualization-json file myself and am having trouble understanding how dendrograms are generated. Is there any guidance you can provide regarding the relationships inside the "groups" array that generates the dendrogram relationships?

**Comment by cornhundred** [comment]
Hi, 

The easiest way to generate the Visualization-JSON would be to use [Clustergrammer-PY](https://github.com/MaayanLab/clustergrammer-py), but you can also generate it on your own. The dendrogram groups are calculated by forming flat clusters from hierarchical clustering, using [`fcluster`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.hierarchy.fcluster.html), at different thresholds. I define ten threshold distances and store the group information in [`cat_clust`](https://github.com/MaayanLab/clustergrammer-py/blob/master/clustergrammer/calc_clust.py#L64). Let us know if you have any questions.

Best,
Nick

**Comment by cornhundred** [comment]
Hi @AndrewGuard, I'm closing the issue based on inactivity. Please let us know if you would like additional help.
