### ISSUE TITLE
Visualization-JSON example

### ISSUE THREAD

**Issue by AndrewGuard** [MaayanLab/clustergrammer#28]
Is there an example of a Visualization-JSON file that has all or most possible configurations? I'm specifically wondering about manipulating chart colors without altering the core clustergrammer.js configuration (tile_colors: ['#FF0000', '#1C86EE'], line 567 in clustergrammer.js), as well as manipulating column and row header sizes.

**Comment by cornhundred** [comment]
Hi Andrew,

There is not currently a way to set matrix cell/tile colors or header size using the Visualization-JSON. You can set category colors (see [categories.py](https://github.com/MaayanLab/clustergrammer-py/blob/f546d829e0f57db9f4bedec9a0a3810f98abdaf7/clustergrammer/categories.py#L95)) through the Visualization-JSON using Clustergrammer-PY, but we have not added customization beyond this. 

Like you said, these features can be set by passing arguments to Clustergrammer-JS. You could try and do this on your own by adding keys to the Visualization-JSON and having this information automatically passed as the appropriate arguments to Clustergrammer-JS.  This however is a feature that we can add in the future. Let us know if that helps and we can let you know when we have added this feature.

Best,
Nick

**Comment by AndrewGuard** [comment]
Thank you, yes this is helpful. It would also be beneficial, if possible, to examine a sample visualization-JSON file that has the appropriate output. Is there a collection of visualization-JSON files online available for analysis?

**Comment by cornhundred** [comment]
Sorry for the late response. You can see an example visualization JSON here: https://github.com/MaayanLab/clustergrammer/blob/master/json/mult_view.json

and it is documented here: https://clustergrammer.readthedocs.io/clustergrammer_js.html#visualization-json
