### ISSUE TITLE
webpack bundle.js doesn't seem to find d3.slider()

### ISSUE THREAD

**Issue by AmirAlavi** [MaayanLab/clustergrammer#29]
I'm trying to incorporate clustergrammer into a plotly-dash component (wrapping it into a React Component).
I'm trying to get a very basic component, which does nothing but import Clustergrammer. I've installed via `npm install clustergrammer` and use it in the React component with `import Clustergrammer from 'clustergrammer';`

However, when I build the component, the resulting bundle.js doesn't seem to have d3.slider defined.

The firefox console has the following error:
`ReferenceError: d3 is not defined`

And here is the problematic line in bundle.js:
`d3.slider = n(261);`

**Comment by cornhundred** [comment]
Hi, 

This is the [line](https://github.com/MaayanLab/clustergrammer/blob/337cbb41f7e9a307c8501ac8924ab523187f5205/src/filters/make_slider_filter.js#L5) where I'm importing `d3.slider`. If I remember correctly, this is just adding a `slider` method to `d3`.  The firefox error you have seems to indicate that `d3` itself is not defined. You can try `npm install d3` or add it to your requirements. Here is the [line](https://github.com/MaayanLab/clustergrammer/blob/master/package-lock.json#L4221) in Clustergrammer's package.json that defines the version of D3 that is needed (Clustergrammer does not work with D3 version 4).

Let us know if that helps. 

Best,
Nick

**Comment by AmirAlavi** [comment]
Hi Nick,
First, thanks so much for responding. I'm very new to javascript web development, so forgive me if I'm asking some of these questions in the wrong place (part of my problem is I'm not sure if there is an issue with npm, with webpack, or with clustergrammer).

I did a `npm ls | grep d3@' and got:
```
│ ├── d3@3.5.17 deduped
├── d3@3.5.17
```
So it seems to already be installed with the correct version (must have installed it when I installed clustergramer)

So my thinking is that for some reason, d3 isn't making it into the bundle.js. So in my component's `package.json`, I added it there:
```
"dependencies": {
    "builder": "3.2.2",
    "clustergrammer": "^1.19.5",
    "copyfiles": "^1.2.0",
    "d3": "^3.5.17",
    "dash-components-archetype": "^0.2.11",
    "prop-types": "^15.5.9",
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
```
Then built the module and ran my application, but still get the same error.
By the way, what I'm doing is building a Dash plugin to incorporate Clustergrammer into a dashboard, following this documentation: https://dash.plot.ly/plugins

I'd appreciate any advice you have, or suggestions for which software developer to go to next.

**Comment by cornhundred** [comment]
Hi Amir, 

No problem, I'm not an expert on webpack either. I could not find where I was requiring `d3` in the source code and I believe this is because I'm telling webpack that `d3` is an 'external' (see [webpack.config](https://github.com/MaayanLab/clustergrammer/blob/master/webpack.config.js#L23) and [webpack documentation](https://webpack.js.org/configuration/externals/)). So, you might be missing this on your `webpack.config` file. Also, I would recommend adding a `debugger;` in your source code so that you can check whether `d3` is defined using the console. 

Let us know if that helps.

**Comment by cornhundred** [comment]
Hi @AmirAlavi, I'm closing the issue based on inactivity. Please let me know if you were able to resolve this.
