### ISSUE TITLE
Annotation column with multiple values

### ISSUE THREAD

**Issue by armadillocommander** [MaayanLab/clustergrammer#32]
Hi,
I'm trying to use Clustergrammer to analyze some proteomics data, each row represent a single protein and the columns are the samples. I want to add a column of annotation (example: KEGG, GOBP, ...) so in the visualization we can do some annotation enrichment analysis for each cluster. 

However, since each protein may belong to multiple gene sets/pathways, the annotation column contains multiple values represent each gene set/pathway the protein belongs to. Is there anyway to let the clustergrammer to treat the annotation as multiple values instead of a whole string?

Thanks!

**Comment by cornhundred** [comment]
Great, let us know if that worked
