### ISSUE TITLE
clustergrammer with Dash?

### ISSUE THREAD

**Issue by scheckley** [MaayanLab/clustergrammer#35]
Can clustergrammer be used with Dash? all my efforts have failed to render the visualisation. how would one approach doing this?

**Comment by cornhundred** [comment]
I have not used Dash before. I will look into it, but it might be useful to ask the Plotly message board.

**Comment by cornhundred** [comment]
@AmirAlavi seems to have figured out how to get Clustergrammer-JS working in Dash here

https://community.plot.ly/t/using-external-js-libraries-in-custom-dash-component/11653

Also, I'm currently developing [Clustergrammer-GL](https://github.com/ismms-himc/clustergrammer-gl) the WebGL re-build of Clustergrammer. This new version handles much more data; see https://nbviewer.jupyter.org/github/ismms-himc/clustergrammer2-notebooks/blob/master/notebooks/3.0_10X_Genomics_2700_Dataset_NBViewer.ipynb

**Comment by cornhundred** [comment]
Hi @scheckley, I'm closing this issue based on inactivity. Please let us know if you have any additional questions.
