### ISSUE TITLE
multiple_clustergrams?? 

### ISSUE THREAD

**Issue by AnaBVA** [MaayanLab/clustergrammer#40]
Hello,
Probably, this is a very silly question, but I couldn't find the documentation. I would like to create the JSON file for multiple clustergrams in order to have all the plots you show using the web app (heatmap plus Column Similarity Matrix and Row Similarity Matrix). 
Right now I'm using the following code in python:

#####
from clustergrammer_widget import *
from clustergrammer import Network
net = Network()
net.load_file('data.txt')
net.cluster()
net.write_json_to_file('viz', 'mult_view.json')
#####
But how can I create the JSON with the other similarity matrix?

Thanks

**Comment by cornhundred** [comment]
Hi @AnaBVA,

You can follow the example here [make_clustergrammer.py](https://github.com/MaayanLab/clustergrammer/blob/master/make_clustergrammer.py#L40), where we use the `sim_mat = True` option in the cluster method. This produces three Viz-JSONs that can be saved to three separate files and used to produce a website like this: https://maayanlab.github.io/clustergrammer/multiple_clustergrams. 

Let us know if this helps. 

Best,
Nick

**Comment by AnaBVA** [comment]
I followed and it worked with your dataset "rc_two_cats.txt" but not with mine. 
The error I got is: 

in make_sim_mat, which_sim: ['row', 'col']
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Python/2.7/site-packages/clustergrammer/__init__.py", line 99, in cluster
    enrichrgram=enrichrgram)
  File "/Library/Python/2.7/site-packages/clustergrammer/make_clust_fun.py", line 69, in make_clust
    sim_net = make_sim_mat.main(net, inst_dm, which_sim, filter_sim, sim_mat_views)
  File "/Library/Python/2.7/site-packages/clustergrammer/make_sim_mat.py", line 13, in main
    filter_sim=filter_sim)
  File "/Library/Python/2.7/site-packages/clustergrammer/make_sim_mat.py", line 53, in dm_to_sim
    filter_sim = adjust_filter_sim(inst_sim_mat, filter_sim)
  File "/Library/Python/2.7/site-packages/clustergrammer/make_sim_mat.py", line 71, in adjust_filter_sim
    inst_series.sort(ascending=False)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'sort'

**Comment by AnaBVA** [comment]
Maybe I create the file in an incorrect format or maybe I am missing something?
Thanks in advance
[clusterg_data.txt](https://github.com/MaayanLab/clustergrammer/files/2858285/clusterg_data.txt)

**Comment by AnaBVA** [comment]
I may create a file in an incorrect format. Could that be the problem?
[clusterg_data.txt](https://github.com/MaayanLab/clustergrammer/files/2858462/clusterg_data.txt)

**Comment by cornhundred** [comment]
This was a bug with Clustergrammer-PY, where we were using a deprecated method to sort a series ([see update](https://github.com/MaayanLab/clustergrammer-py/blob/c7c98c9910db7c296d513fa4a32f271b54b89fdd/clustergrammer/make_sim_mat.py#L71)). Upgrading Clustergrammer-PY to 1.13.6 (`pip install --upgrade clustergrammer`) should solve your problem. Let us know if that worked. Also, your data format is good and works for me.

**Comment by AnaBVA** [comment]
Awesome! it worked. Thanks, it's an amazing tool.

**Comment by cornhundred** [comment]
Glad it worked and thanks for raising the issue!
