### ISSUE TITLE
stable sorting on categories

### ISSUE THREAD

**Issue by curlup** [MaayanLab/clustergrammer#49]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to sort on one category to get groups view. But also to sort on another category within those groups. Because it's impossible and Clustergrammer will ignore previous order. 

**Describe the solution you'd like**
I would like the sorting on categories to if possible preserve the previous order of items (columns or rows). That is called "stable sorting". And it is a common feature in table data processors, as it allows to do nested sorts.

**Additional context**
So here's an example where it is not performing a stable sorting now (taken from http://maayanlab.github.io/clustergrammer/scrolling_tour):
1. I sorted by Gender:
![Screen Shot 2019-12-05 at 11 00 18 AM](https://user-images.githubusercontent.com/338607/70251957-838a7a80-174e-11ea-80e7-09d3c65811b1.png)

1. then I sorted by "Category" in a hope that samples will stay sorted by Gender within each Category. But they don't:
![Screen Shot 2019-12-05 at 11 00 29 AM](https://user-images.githubusercontent.com/338607/70252021-a452d000-174e-11ea-917d-e3a8925d5b8a.png)

**Comment by cornhundred** [comment]
Hi @curlup that sounds good. I am actively developing the new webgl version of [clustergrammer-gl](https://github.com/ismms-himc/clustergrammer-gl) so this feature will be implemented there first (and on the corresponding new Jupyter Widget [clustergrammer2](https://github.com/ismms-himc/clustergrammer2)

**Comment by cornhundred** [comment]
@curlup clustergrammer-gl version 0.19.0 allows users to sort on a primary category and then also sort on a secondary category. The secondary category is by default the "lower" category and if no lower category exists then is set to the upper category. We might set up an additional option where double-clicking sequential categories will give the option to make primary/secondary/third sorting option. Let us know if have any issues.

**Comment by curlup** [comment]
Nice.

Any plans to backport? 
Or just fix it to be stable in non-gl version?

**Comment by cornhundred** [comment]
Hi @curlup, we don't have explicit plans to backport but I can have a look at it and see if we can quickly fix the issue.

**Comment by curlup** [comment]
right, would be awesome if it's not too much trouble. 
I'm not sure when/if we will have time to migrate to new version, and having stable sorting would be a bliss.

I can dig around myself (not that im a great at js but this shouldnt be supa hard, right?) if you will consider accept it later as backport fix
