### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by alexlenail** [MaayanLab/clustergrammer#51]
`.ix` was dropped from pandas a few versions ago. It would be nice if clustergrammer worked with modern pandas.

**Comment by cornhundred** [comment]
Thanks @alexlenail we have made this update to the new Clustergrammer2 https://github.com/ismms-himc/clustergrammer2 python package/widget. We will update this package later and are focusing our efforts on the new version. 

Let us know if that works for you.

**Comment by alexlenail** [comment]
Wonderful, thank you!
