### ISSUE TITLE
clustergrammer.js with require.js?

### ISSUE THREAD

**Issue by paul-shannon** [MaayanLab/clustergrammer#6]
Any chance your team already has a minimal example lying around of using clustergrammer with require.js?

Thanks!

 - Paul

**Comment by cornhundred** [comment]
Sorry, we do not. But it can be used with node package manager - see the webpack example from clustergrammer-widget: https://github.com/MaayanLab/clustergrammer-widget/blob/master/js/package.json 

I think you should be able to do something similar (to webpack) with require.js.

- Nick

**Comment by paul-shannon** [comment]
Thanks, Nick.  I’ll look into the npm support.   One additional question, if I may:  does clustergrammer support the AMD?

 - Paul

**Comment by cornhundred** [comment]
No problem. I'm not familiar with asynchronous module definition so I do not think it does. 

-Nick

**Comment by paul-shannon** [comment]
Hi Nick,  

I am till interested in using clustergrammer.js with requirejs.    Here's the context: I am creating a jupyter-widget "multiWidget" which combines igv.js, cytoscape.js, three.js, leaflet, a simple d3 plotter, all as individual tabs within standard [jQuery UI Tabs](https://jqueryui.com/tabs/).  I want to add clustergrammer since an interactive heatmap/clustering tool is essential to our projects.  

Events (i.e., selections) made in the cytoscape tab could be echoed to the igv track, to an expression matrix in clustergrammer, to epidemiogical data in the leaflet tab map, to 3D PCA in the three.js tab.

At present I have all of these libraries adapted to the requirejs AMD style using [shims](http://requirejs.org/docs/api.html#config-shim).  Some of them combine gracefully in jQuery tabs, in a jupyter notebook.  Others seem to need more configuration of their shims in order to eliminate conflicts with jQuery (perhaps due to the use of global variables in jQuery).  There is some fuss to sort through, but the basic rich Jupyter multiWidget seems like it will work.

requirejs is mostly straightforward.  Here for example is the entire requirejs AMD-ification of leaflet, displaying a map of Seattle:
````
require.config({
    paths: {
      'leaflet': 'https://unpkg.com/leaflet@1.0.2/dist/leaflet'
       },
    shim: {
       leaflet: {
          exports: 'L'
           },
        } })

require(['leaflet'], function (L) {
  seattle = {lat: 47.59,    long: -122.335167, zoom: 12};
  denver  = {lat: 39.74739, long: -105,        zoom: 13};
  loc = seattle;

  var map = L.map('mapDiv').setView([loc.lat, loc.long], loc.zoom);
  var mapURI = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw';

  L.tileLayer(mapURI, {
             maxZoom: 18,
             attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                           '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                           'Imagery © <a href="http://mapbox.com">Mapbox</a>',
             id: 'mapbox.light'
     }).addTo(map);
  }); // require
````
 Add to this a simple bit of html and all the richness of the leaflet library is ready to use:
````
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>leaflet require single</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
<script data-main="app" src="http://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>
<style>
#mapDiv{
  border: 1px solid blue;
  width: 1000px;
  height: 1000px;
  }
</style>
</head>
<body>
   <div id="mapDiv"></div>
</body>
</html>
````

This approach makes non-AMD libraries available, and ready to combine in interesting ways.   How hard would it be to present clustergrammer in this style?  Would you and your team have any interest in doing this?

Thanks -

 - Paul

**Comment by cornhundred** [comment]
Thanks for the information Paul, I'll look into it and keep you updated. 

Nick

**Comment by paul-shannon** [comment]
Hi Nick,

Sorry to pester.   Any chance you will be able to get around to this?

 - Paul

**Comment by cornhundred** [comment]
Hi Paul,

Sorry I haven't gotten to it yet. I'm hoping to get to it within the upcoming week.

Nick

**Comment by cornhundred** [comment]
Hi @paul-shannon 

I was able to get Clustergrammer to work with RequireJS and an example page can be found here:

[https://github.com/MaayanLab/clustergrammer_requirejs](https://github.com/MaayanLab/clustergrammer_requirejs)

I needed to shim the non-AMD version of underscore, but Clustergrammer loaded without this ... so I guess it supports AMD. 

Let me know if this is working for you. I think that you can just use the [clustergrammer.js](https://github.com/MaayanLab/clustergrammer/blob/master/clustergrammer.js) file as is with RequireJS. One thing to keep in mind is the Clustergrammer works with D3 version 3, but not version 4 yet (the library versions in the above repo should work). 

Also, I recently wrote up documentation ([clustergrammer.readthedocs.io](http://clustergrammer.readthedocs.io/)) for the entire project if you would like to have a look. 

- Nick

**Comment by paul-shannon** [comment]
Nick,

Terrific!  Trying this now.   I assume I can create a properly structured json matrix, in memory, and pass that (as a variable, rather than a filename) to clustergrammer also?

 - Paul

**Comment by cornhundred** [comment]
Paul, 

Yeah, you pass the [visualization JSON](http://clustergrammer.readthedocs.io/clustergrammer_js.html?highlight=json#visualization-json) as a variable. 

I will be adding support for a more compact JSON format (currently the format is network-like, with nodes and links ... it is more compact to simply have a matrix). But I have to make changes to the python and JavaScript ends. I can let you know when this has been done and you can just get the latest versions. 

- Nick

**Comment by paul-shannon** [comment]
Great.  It’s no trouble to forge a visualization JSON object on the fly, so I will go for that now.   The matrix argument will be very useful when it is ready.  

Many thanks for this, Nick.    It arrives at just the right time.  

 - Paul

**Comment by cornhundred** [comment]
Paul, 

No problem, thanks for the reminder. Are you using the python library [clustergrammer.py](https://github.com/MaayanLab/clustergrammer-py) to make the visualization JSON? Cause this will get you from input matrix to JSON (see [Clustergrammer-PY](http://clustergrammer.readthedocs.io/clustergrammer_py.html))

- Nick

**Comment by paul-shannon** [comment]
Hi Nick,

I am using clustergrammer.py now - thanks for the tip.  It works well.

I have been reshaping the example in the github repo into a form a bit more familiar to me.  Everything works, very nice.

That structure is:

   index.html
   app.js
   libs/clustergrammer.js
   fonts/6 fontawesome files
   css/boostrap, custom, font-awesome

I do have one question.  It appears that d3 is needed within two AMD modules: my somewhat distilled app.js (see below) and clustergrammer.js.  However, if I do not <script src=“d3…”> in index.html, but instead only in app.js, then clustergrammer.js does not find d3.

How do I structure this simple app so that d3 is seen both by app.js and clustergrammer.js?   Is this a webpack technique?

 - Paul

— index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>clustergrammer require single</title>
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/custom.css" />
    
<script data-main="app" src="http://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.2/require.min.js"></script>
</head>
<body>
   <div id="cgDiv">
      <h1 class='wait_message'>Please wait ...</h1>
  </div>
</body>
</html>

—— app.js
require.config({
    paths: {
        'underscore'    :  'libs/underscore-min',
        'jquery'        :  'http://code.jquery.com/jquery-1.12.4.min',
        'd3'            :  'http://cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
        'clustergrammer':  'libs/clustergrammer'
        },
    shim: {underscore: {
             exports: '_'
             }}
   });

require(['underscore', 'jquery', 'd3', 'clustergrammer'], function (_, $, d3, clustergrammer) {
   // more code here

**Comment by cornhundred** [comment]
This last question was taken care of in: 

https://github.com/MaayanLab/clustergrammer_requirejs/pull/1
