### ISSUE TITLE
max tree levels 11?

### ISSUE THREAD

**Issue by paul-shannon** [MaayanLab/clustergrammer#8]
Hi NIck,

In our early testing of RClustergrammer we encountered a matrix of single cell neuron rna-seq data.  When we cluster in R (using the base R hclust function) we get back a hierachical tree of 187 (!) levels.   

The max tree depth level in Clustergrammer appears to be 11.    

Is this configurable?   We are getting by right now by truncating our tree, from the top or the bottom, to 11 levels, but we lose lots of information.

Thanks!

 - Paul

**Comment by cornhundred** [comment]
Hi Paul, 

I'm constructing groups by taking 11 slices from the dendrogram (spread out evenly over the height of the dendrogram). You can see this here (see lines 71-75): https://github.com/MaayanLab/clustergrammer-py/blob/master/clustergrammer/calc_clust.py#L71

You might want to do something similar in RClustergrammer.

Later we might allow the number of slices to be configured. 

Best,
Nick

**Comment by paul-shannon** [comment]
Thanks, Nick.  That ought to work for us too.  I cast a vote for configuring the number of slices, once time permits.

 - Paul

**Comment by paul-shannon** [comment]
HI Nick,

Reopening this, if I may...

I have been experimenting with subsampling the full hclust tree with an rna-seq matrix with 803 columns - 803 samples.  The difficulty I encounter would, I think, be present as well with only 100 columns:  I cannot imagine an a priori algorithm  to select the 11 tree branches (corresponding to the 11 steps in the Clustergrammer UI) which include all of the  _interesting_ clusters.   This is in part because _interesting_ changes with context.  

I have rewritten my R code so I can request different sets of 11 branches, but even that flexibility leaves a lot to be desired: to choose the best 11 branchings from hundreds of possible ones requires context, and some artful guesses about which branches include most (all?) of the interesting clusters revealed the in the clustergrammer heatmap.

Or maybe there is a solution I am missing?

Here is a screenshot of the column clusters, which shows that possibly interesting clusters are at different levels of the tree.   We'd like to be able to select any one of these.

It seems downright greedy of me - sorry! - but may I ask for this feature?  That is, that the max number of branching levels be unbounded, driven by the data?   clustergrammer would be really useful to my collaborators, and to future Bioconductor users, if this feature could be implemented.  
Or is there  another solution already available I could use?

Thanks!

 - Paul
![clustergrammer](https://user-images.githubusercontent.com/2480712/29341547-dc3791d4-81d9-11e7-8a83-35605f4c5a3a.png)


![screen shot 2017-08-15 at 4 24 31 pm](https://user-images.githubusercontent.com/2480712/29341507-8c3b3118-81d9-11e7-9656-5f10ddf9e139.png)

**Comment by cornhundred** [comment]
Hi Paul, 

Thanks for the feedback. Just to make sure we are talking about the same thing, Clustergrammer takes 11 slices out of the dendrogram tree spaced evenly throughout the height of the tree. Clustergrammer does not choose a subset of branches, but instead slices through all branches present at a given height/distance. This results in sets of clusters that highlight large and small scale clustering in the data (e.g. slices taken at the top of the tree give few large clusters, while slices taken out of the bottom of the tree give many small clusters). And the slider (blue circle and gray triangle) lets users toggle between slices and clusters defined at different levels in the tree.

However, some information in the dendrogram is lost by only taking 11 slices. We might set up a user interface to allow users to cut the tree at arbitrary heights or take as many slices as there are branch points in the dendrogram. But in the short term we will likely just take more slices of the dendrogram (maybe ~50 - 100 slices) and make these available to the user to toggle between. 

Let us know if that sounds like what you want. 

Best,
Nick

**Comment by paul-shannon** [comment]
Hi Nick,

Thanks for considering this.  The “choose a subset of branches” operation I mentioned, which you ask about: we do that in R before sending the data to the browser.    We  use the standard base R hclust function to compute the dendrogram, and the companion function “cutree” to select 11 branches (slices) for clustergrammer to display.  Then we build out the JSON structure clustergrammer expects, and send it to the browser for rendering and exploration.  

Here’s what I’d really like to see :} - but this may be a case of me being (too) greedy.  I believe that all of the structure contained in the dendrogram is useful, and so trimming it down - subsampling - causes us to lose information.

I have been impressed by the robustness, large-scale data handling and speed of clustergrammer.   No bugs, smooth operation, no difficulty with large matrices.   This lulls me into thinking that your code and the browser might well be able to handle full dendrograms, even those with hundreds of levels, hundreds of branches.  

Whatever direction you choose, perhaps you could include a readout for rows and columns which reports the current level of the displayed slice?  And perhaps even a function in the API which allows this to be set programmatically.  Both of these would be useful for reproducibility and collaboration, for instance:  “evaluate the clusters you see when the x dendrogram is set to 45, y to 10; those genes in those samples reveal an interesting pattern”.

Please consider these ideas as quite possibly only food for thought, offered in brainstorming mode.  We will be eager to use whatever solution you come up with.

 - Paul

**Comment by cornhundred** [comment]
Hi Paul, 

Thanks for the feedback. I think that makes a lot of sense, especially the part about initializing the dendrogram slices. I should be able to implement more slices in the short term (hopefully a month or so) and then over the longer term implement a method to save the whole tree and allow slices at all branching heights and/or arbitrary heights (as well as readouts of the branch height distance). 

We're also working on front-end re-clustering (see reclustering branch https://github.com/MaayanLab/clustergrammer/network), which will enable users to re-cluster after arbitrary filtering (e.g. filtering out a specific category). So co-incidentally, I'm also re-implementing this dendrogram slicing on the JavaScript end and will take your requests for improved slicing into consideration 😄. 

Best,
Nick

**Comment by paul-shannon** [comment]
All sounds good, Nick.   Thanks!

 - Paul

**Comment by paul-shannon** [comment]
Hi Nick,

Sorry to pester.  I'm sure you are busy with a dozen things...

May I ask if you have had any time to work on this?  Or see the chance up ahead to do so?

Thanks!

 - Paul

**Comment by cornhundred** [comment]
Hi Paul, 

Sorry for the delays, but other things have taken higher priority for the time being. I will probably bundle dendrogram improvements with a release that includes front-end re-clustering (they are sort of related) and this should hopefully get released in ~ a month, but can't guarantee. I'll definitely let you know when the new release is ready. 

Best,
Nick

**Comment by cornhundred** [comment]
Hi @paul-shannon, I'm closing this issue since this features will be implemented in Clustergrammer-GL first (see https://github.com/ismms-himc/clustergrammer-gl/issues/30) and possibly implemented here for Clustergrammer-JS.
